### PR TITLE
Mini correction d'accord dans le readme.md

### PR DESCRIPTION
**Pull request by loup-brun**
l'utilisateur ghqc vous ~~suit~~ **suit**

### CODE REVIEW

**Comment by millette** [comment]
Merci @loup-brun

**Comment by Sirlupinwatson1** [comment]
Can i clone this bot please 📟

**Comment by millette** [comment]
@Sirlupinwatson1 I'd rather not share it. See #1 if you read French or email me to discuss.

**Comment by Sirlupinwatson1** [comment]
Thanks sir, yes I speak french. I am a bit too enthousiaste

**Pull request merged**
